### ISSUE TITLE
Make wall transparent if hero is behind it.

### ISSUE THREAD

**Issue by igorko** [dorkster/flare-engine-next#11]
Migrated from https://github.com/clintbellanger/flare-engine/issues/946

We still should see avatar if he is behind walls.

**Comment by dorkster** [comment]
I've since implemented https://github.com/flareteam/flare-engine/commit/66a554514b814b1f622e3e88cf3ff7a68f2bf0cf as an alternative. I personally prefer it visually over making tiles transparent (my reasoning can be found in [this thread](https://github.com/flareteam/flare-engine/issues/1674#issuecomment-425282953)).
